#!/usr/bin/env python3
"""Generate model/sysml/uas_security.sysml from the traceability CSVs.

Threats become `concern`s, requirements become `requirement`s that `frame`
their parent threats and are `satisfy`-ed by their allocated component, and
verification events become `verification` cases that `verify` requirements.
Element references resolve through the alias index in uas_architecture.sysml;
every element ID in data/elements.csv must have an alias there.

    python tools/gen_sysml.py           # regenerate the file
    python tools/gen_sysml.py --check   # exit 1 if it is stale or an alias is missing

Standard library only.
"""
from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
ARCH = ROOT / "model/sysml/uas_architecture.sysml"
OUT = ROOT / "model/sysml/uas_security.sysml"
sys.path.insert(0, str(ROOT / "tools"))
from validate_trace import split_multi  # noqa: E402

ALIAS = re.compile(r"^\s*alias '([A-Z0-9-]+)' for ([A-Za-z0-9_:]+);", re.M)
TB_LITERAL = re.compile(r"enum <'(TB-\d{2})'>")
# Enum literals are always quoted: some values (accept, analysis) are SysML keywords.
STRIDE = {"S": "spoofing", "T": "tampering", "R": "repudiation",
          "I": "informationDisclosure", "D": "denialOfService", "E": "elevationOfPrivilege"}
METHOD = {"I": "inspection", "A": "analysis", "D": "demonstration", "T": "test"}


def read(name: str) -> list[dict]:
    with (DATA / name).open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def doc(text: str) -> str:
    return text.replace("*/", "* /")


def string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def aliases() -> tuple[dict[str, str], set[str], list[str]]:
    text = ARCH.read_text(encoding="utf-8")
    index = dict(ALIAS.findall(text))
    boundaries = set(TB_LITERAL.findall(text))
    problems = []
    for e in read("elements.csv"):
        eid = e["element_id"]
        if e["type"] == "trust_boundary":
            if eid not in boundaries:
                problems.append(f"{eid}: no TrustBoundary literal <'{eid}'> in {ARCH.relative_to(ROOT)}")
        elif eid not in index:
            problems.append(f"{eid}: no alias in {ARCH.relative_to(ROOT)}")
    return index, boundaries, problems


def feature_path(alias_target: str) -> str:
    """uasSystem::a::b -> UAS_Architecture::uasSystem.a.b (dot notation for satisfy)."""
    first, *rest = alias_target.split("::")
    return "UAS_Architecture::" + ".".join([first, *rest])


def generate(index: dict[str, str]) -> str:
    threats, reqs = read("threats.csv"), read("requirements.csv")
    events = read("verification.csv")
    parents: dict[str, list[str]] = {}
    for link in read("trace.csv"):
        parents.setdefault(link["req_id"], []).append(link["threat_id"])

    out = [
        "// GENERATED by tools/gen_sysml.py from data/*.csv. Do not edit by hand.",
        "// Threats are concerns; requirements frame their parent threats and are",
        "// satisfied by their allocated component; verification cases verify them.",
        "package UAS_Security {",
        "    private import ScalarValues::*;",
        "    private import UAS_Architecture::*;",
        "",
        "    enum def MissionImpact { enum 'MI-1'; enum 'MI-2'; enum 'MI-3'; enum 'MI-4'; }",
        "    enum def StrideCategory { " + " ".join(f"enum <{k}> '{v}';" for k, v in STRIDE.items()) + " }",
        "    enum def Disposition { enum 'mitigate'; enum 'accept'; }",
        "    enum def VerificationMethod { " + " ".join(f"enum '{v}';" for v in METHOD.values()) + " }",
        "",
        "    concern def Threat {",
        "        attribute missionImpact : MissionImpact;",
        "        attribute stride : StrideCategory;",
        "        attribute disposition : Disposition;",
        "    }",
        "    requirement def SecurityRequirement {",
        "        attribute method : VerificationMethod;",
        "        attribute evidenceRepo : String;",
        "        attribute resiliencyApproach : String[0..*];",
        "    }",
        "    verification def SecurityVerification {",
        "        attribute method : VerificationMethod;",
        "        attribute evidenceRepo : String;",
        "    }",
        "",
        f"    // {len(threats)} threats (docs/05-threat-model.md)",
    ]
    for t in threats:
        tid = t["threat_id"]
        out += [
            f"    concern '{tid}' : Threat {{",
            f"        doc /* {doc(t['title'])}. {doc(t['description'])} */",
        ]
        if t["acceptance_rationale"]:
            out.append(f"        comment acceptanceRationale /* {doc(t['acceptance_rationale'])} */")
        out += [
            f"        attribute :>> missionImpact = MissionImpact::'{t['mission_impact']}';",
            f"        attribute :>> stride = StrideCategory::'{STRIDE[t['stride']]}';",
            f"        attribute :>> disposition = Disposition::'{t['disposition']}';",
            "    }",
            f"    dependency from '{tid}' to UAS_Architecture::'{t['element_id']}';",
        ]

    out += ["", f"    // {len(reqs)} requirements (docs/07-requirements.md)"]
    for r in reqs:
        rid = r["req_id"]
        approaches = split_multi(r["resiliency_approach"])
        out += [
            f"    requirement '{rid}' : SecurityRequirement {{",
            f"        doc /* {doc(r['statement'])} */",
            f"        comment rationale /* {doc(r['rationale'])} */",
        ]
        out += [f"        frame '{tid}';" for tid in parents.get(rid, [])]
        out += [
            f"        attribute :>> method = VerificationMethod::'{METHOD[r['verification']]}';",
            f"        attribute :>> evidenceRepo = {string(r['evidence_repo'])};",
        ]
        if approaches:
            out.append("        attribute :>> resiliencyApproach = (" + ", ".join(string(a) for a in approaches) + ");")
        out += [
            "    }",
            f"    satisfy '{rid}' by {feature_path(index[r['allocated_to']])};",
        ]

    out += ["", f"    // {len(events)} verification events (docs/08-verification-plan.md)"]
    for v in events:
        out += [
            f"    verification '{v['ve_id']}' : SecurityVerification {{",
            f"        doc /* {doc(v['title'])}. Pass: {doc(v['pass_criteria'])} */",
            "        objective {",
        ]
        out += [f"            verify '{rid}';" for rid in split_multi(v["req_ids"])]
        out += [
            "        }",
            f"        attribute :>> method = VerificationMethod::'{METHOD[v['method']]}';",
            f"        attribute :>> evidenceRepo = {string(v['evidence_repo'])};",
            "    }",
        ]
    out.append("}")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the generated model is stale or an alias is missing")
    args = parser.parse_args(argv)

    index, _, problems = aliases()
    for p in problems:
        print(f"ERROR   {p}")
    if problems:
        return 1
    text = generate(index)
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"STALE   {OUT.relative_to(ROOT)}: run python tools/gen_sysml.py")
            return 1
        print("SysML security model up to date; every element has an alias")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
